project:
  type: website

website:
  title: "M. Y. Eichlersmith"
  navbar:
    background: primary 
    left:
      - href: current.qmd
        text: Current
      - href: experience.qmd
        text: Experience
  page-footer:
    left: Created using [Quarto](https://quarto.org/) by [RStudio](https://www.rstudio.com/)
    center:
      - <img src="logo.png" style="height:3.5em;">
      - <div class = "footertxt">IBIQUE IN<br>COLLIS RESISTO</div>
    right:
      - icon: github
        href: https://github.com/MarEichler/mye-website
        aria-label: Website GitHub

format:
  html:
    theme: 
    - cosmo
    - www/styles.scss
    toc: true

editor: source

